In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import scale
import numpy as np

In [2]:
data = pd.read_csv("clustering_Data_2018.csv")

In [3]:
data.head()

GEO           COUNTRY  ABS_MARGIN_MAX  ABS_MARGIN_AVG  \
0  AP          IN                       3910230          159443   
1  AP          KR                       3701398           63970   
2  AP                        LK          349036          192876   
3  AP          TW                        235085           31938   
4  AP          HK                        518952           20408   

   ABS_MARGIN_SUM SUBGROUP  
0        34758581   XLARGE  
1        11770533   XLARGE  
2          385753   XLARGE  
3         3353529    LARGE  
4         1571421    LARGE

In [4]:
x = data.drop(['SUBGROUP','GEO','COUNTRY'],axis = 1).values

In [5]:
x = scale(x)


C:\Users\PranaviPadegal\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


In [6]:
clustering = KMeans(n_clusters = 5,random_state= 1)

In [7]:
clustering.fit(x)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=5, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=1, tol=0.0001, verbose=0)

In [8]:
clustering.labels_

array([3, 2, 0, 1, 1, 4, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 4, 4, 4, 4, 1, 4,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 4, 4, 4, 4, 0, 1, 1,
       0, 1, 4, 4, 4, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 4, 1, 4,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [9]:
idx = np.argsort(clustering.cluster_centers_.sum(axis=1))
lut = np.zeros_like(idx)
lut[idx] = np.arange(5)

In [10]:
clustering.cluster_centers_.sum(axis=1)

array([ 2.50199832, -1.33570774,  6.95966717, 13.21225035,  1.43956575])

In [11]:
idx

array([1, 4, 0, 2, 3], dtype=int64)

In [12]:
y = pd.DataFrame(clustering.labels_)

In [13]:
y.columns = ['Subgroup_pred']

In [14]:
data['predicted_subgroup'] = y['Subgroup_pred']

In [17]:
data.to_csv("Subgroup_2018.csv")