In [12]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import scale
import numpy as np

In [13]:
data = pd.read_csv("mergeddata_17&18.csv")

In [14]:
data.head()

ABS_MARGIN_MAX  ABS_MARGIN_AVG  ABS_MARGIN_SUM         geo  \
0         6572729          125362        58947687  AP           
1         3934183           44128        18886274  AP           
2          777781           28931         9419587  AP           
3          648627           17106         4235393  AP           
4          737064           65372         6994830  AP           

            country  SUBGROUP  
0  IN                       4  
1  KR                       4  
2  TW                       3  
3  HK                       3  
4  ID                       3

In [15]:
data.shape

(70, 6)

In [16]:
data.dtypes

ABS_MARGIN_MAX     int64
ABS_MARGIN_AVG     int64
ABS_MARGIN_SUM     int64
geo               object
country           object
SUBGROUP           int64
dtype: object

In [17]:
x = data.drop(['SUBGROUP','geo','ABS_MARGIN_MAX','ABS_MARGIN_AVG','country'],axis = 1).values

In [18]:
x = scale(x)

C:\Users\PranaviPadegal\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


In [19]:
Y = np.array(data.SUBGROUP)

In [20]:
clustering = KMeans(n_clusters = 5,random_state= 1)

In [21]:
clustering.fit(x)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=5, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=1, tol=0.0001, verbose=0)

In [22]:
clustering.labels_

array([1, 3, 4, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 3, 4, 3, 0, 4, 4, 0, 0,
       4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 4, 3, 4, 4, 4, 0, 3, 4, 4, 3,
       4, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 0, 0,
       0, 0, 0, 0])

In [24]:
y = pd.DataFrame(clustering.labels_)

In [26]:
y.columns = ['Sub-group']

In [30]:
data['Predicted'] = y['Sub-group']

In [27]:
Y

array([4, 4, 3, 3, 3, 3, 2, 3, 1, 2, 1, 2, 1, 1, 4, 3, 3, 2, 2, 3, 2, 1,
       2, 2, 0, 1, 1, 3, 0, 0, 0, 0, 4, 3, 3, 3, 2, 2, 2, 1, 4, 2, 2, 4,
       3, 2, 1, 2, 1, 2, 0, 1, 0, 0, 1, 4, 2, 4, 2, 4, 2, 3, 3, 3, 2, 2,
       2, 2, 1, 1], dtype=int64)

In [31]:
np.sum(clustering.labels_ == Y)


10

In [34]:
is_0 =  data['Predicted']==0

In [35]:
data_zero = data[is_0]

In [36]:
data_zero.shape

(40, 7)

In [37]:
is_1 = data['Predicted'] == 1
data_one = data[is_1]
data_one.shape

(3, 7)

In [38]:
is_2 = data['Predicted'] == 2
data_two = data[is_2]
data_two.shape

(1, 7)

In [39]:
is_3 = data['Predicted'] ==3
data_three = data[is_3]
data_three.shape

(8, 7)

In [41]:
is_4 = data['Predicted'] ==4
data_four = data[is_4]
data_four.shape

(18, 7)

In [42]:
data_four['ABS_MARGIN_SUM'].max()

12479465

In [43]:
data_four['ABS_MARGIN_SUM'].min()

4812799

In [44]:
data_three['ABS_MARGIN_SUM'].max()

27202219

In [45]:
data_three['ABS_MARGIN_SUM'].min()

17934786

In [46]:
data_two['ABS_MARGIN_SUM'].max()

117059545

In [47]:
data_two['ABS_MARGIN_SUM'].min()

117059545

In [48]:
data_one['ABS_MARGIN_SUM'].max()

58947687

In [49]:
data_one['ABS_MARGIN_SUM'].min()

35974908

In [50]:
data_zero['ABS_MARGIN_SUM'].max()

4242358

In [51]:
data_zero['ABS_MARGIN_SUM'].min()

64933

In [55]:
data.to_csv('Merged_data.csv')

In [46]:
y_predicted

array([2, 2, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 2, 1, 2, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 1, 2, 1, 1, 1, 0, 2, 1, 1, 2,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0])

In [47]:
np.sum(y_predicted== Y)

8

In [89]:
18/68

0.2647058823529412