In [15]:
import pandas as pd
from collections import Counter
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import re
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier, MLPRegressor

In [16]:
df = pd.read_csv("details_All.csv",encoding='latin-1')

C:\Users\PranaviPadegal\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (12,36,37,38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [17]:
data = df[['MONTH','BID_ID',"SOURCE_SYS_CD","PRICE_TO_BP","BID_MARGIN_TOTAL","BID_MARGIN","BID_DISCOUNT","STOP_BIDS","BPCOPS",
            "MISSING","COUNTRY","CONFIDENTIALITY","ROUTE_TO_MARKET","NON_COMPETITIVE_BID","OFF_SHORE_PMT_TERMS","BUNDLED_SOLUTION",
            "CONTINGENCY_FEE","FOCUS","HW_SW"]]

In [18]:
data = data[pd.notnull(data['COUNTRY'])]
#df.replace({"":np.nan}, inplace=True)
#df.fillna(df.mode().iloc[0])

In [19]:
new_data =  data.replace({"(null)":np.nan})

In [20]:
new_data.isnull().values.sum()

51772

In [21]:
new_data = new_data.fillna(new_data.mode().iloc[0])

In [22]:
new_data.shape

(27406, 19)

In [23]:
#new_data['BID_ID'] = new_data['BID_ID'].map(lambda x: re.sub(r'\W+', '', x))

In [24]:
new_data.head()

MONTH            BID_ID SOURCE_SYS_CD  PRICE_TO_BP BID_MARGIN_TOTAL  \
0      4  10aile4v-OaP8200          OPRA   34236.8000        1027.1035   
1      9  10aile4v-OaP8640          OPRA   58588.0200        6184.2853   
2      6  10aile4v-OaP8404          OPRA   57095.8465        1841.8015   
3      9  10aile4v-OaP8630          OPRA  122709.3530        5734.7869   
4      9  10aile4v-OaP8642          OPRA  122709.3530        5812.2884   

  BID_MARGIN BID_DISCOUNT  STOP_BIDS  BPCOPS  MISSING COUNTRY CONFIDENTIALITY  \
0    2.91262     96.73474          0       0        1      TW               N   
1    9.54773     97.12923          0       0        0      TW               N   
2      3.125     97.42264          0       0        0      TW               N   
3    4.46481     96.40123          0       0        0      TW               N   
4    4.52242     96.40123          0       0        0      TW               N   

  ROUTE_TO_MARKET NON_COMPETITIVE_BID OFF_SHORE_PMT_TERMS BUNDLED_SOLUTION  \
0               N                   N                   N                N   
1               N                   N                   N                N   
2               N                   N                   N                N   
3               N                   N                   N                N   
4               N                   N                   N                N   

  CONTINGENCY_FEE  FOCUS HW_SW  
0               N      0    HW  
1               N      0    HW  
2               N      0    HW  
3               N      0    HW  
4               N      0    HW

In [25]:
#new_data['BID_ID'] = new_data.BID_ID.str.replace(r'\D+', '')


In [26]:
new_data.isnull().values.sum()

0

In [27]:
new_data.tail()

MONTH                                             BID_ID SOURCE_SYS_CD  \
27415      6  KR6442382                                     ...       EPRICER   
27416      9  KR6821226                                     ...       EPRICER   
27417      9                                         8500209367            BH   
27418      9                                         8500209719            BH   
27419     11                                   10aile4v-OaP7911          OPRA   

       PRICE_TO_BP BID_MARGIN_TOTAL BID_MARGIN BID_DISCOUNT  STOP_BIDS  \
27415   67172.4878       11853.9697         15         83.5          0   
27416  266045.4808       26312.1907          9         86.4          0   
27417   24584.6800          3038.53         11        99.28          0   
27418  191816.7600        32661.549      14.55      99.6548          0   
27419  226953.1980       41215.5854   15.36927       83.607          0   

       BPCOPS  MISSING COUNTRY CONFIDENTIALITY ROUTE_TO_MARKET  \
27415       0        0      KR               N               N   
27416       0        0      KR               N               N   
27417       0        0      CN               N               N   
27418       0        0      CN               Y               N   
27419       0        1      TW               N               N   

      NON_COMPETITIVE_BID OFF_SHORE_PMT_TERMS BUNDLED_SOLUTION  \
27415                   N                   N                N   
27416                   N                   N                N   
27417                   N                   N                N   
27418                   N                   N                Y   
27419                   N                   N                N   

      CONTINGENCY_FEE  FOCUS HW_SW  
27415               N      0    HW  
27416               N      1    HW  
27417               N      0    HW  
27418               N      1    HW  
27419               N      1    HW

In [28]:
new_data.dtypes

MONTH                    int64
BID_ID                  object
SOURCE_SYS_CD           object
PRICE_TO_BP            float64
BID_MARGIN_TOTAL        object
BID_MARGIN              object
BID_DISCOUNT            object
STOP_BIDS                int64
BPCOPS                   int64
MISSING                  int64
COUNTRY                 object
CONFIDENTIALITY         object
ROUTE_TO_MARKET         object
NON_COMPETITIVE_BID     object
OFF_SHORE_PMT_TERMS     object
BUNDLED_SOLUTION        object
CONTINGENCY_FEE         object
FOCUS                    int64
HW_SW                   object
dtype: object

In [29]:
#new_data['bid_id'] = new_data['bid_id'].astype(int)
new_data['BID_MARGIN_TOTAL'] = new_data['BID_MARGIN_TOTAL'].astype(float)
new_data['BID_MARGIN'] = new_data['BID_MARGIN'].astype(float)
new_data['BID_DISCOUNT'] = new_data['BID_DISCOUNT'].astype(float)

In [30]:
new_data.dtypes

MONTH                    int64
BID_ID                  object
SOURCE_SYS_CD           object
PRICE_TO_BP            float64
BID_MARGIN_TOTAL       float64
BID_MARGIN             float64
BID_DISCOUNT           float64
STOP_BIDS                int64
BPCOPS                   int64
MISSING                  int64
COUNTRY                 object
CONFIDENTIALITY         object
ROUTE_TO_MARKET         object
NON_COMPETITIVE_BID     object
OFF_SHORE_PMT_TERMS     object
BUNDLED_SOLUTION        object
CONTINGENCY_FEE         object
FOCUS                    int64
HW_SW                   object
dtype: object

In [31]:
new_data=pd.get_dummies(new_data, columns=['COUNTRY'])
#del data_1['COUNTRY_']

In [32]:
new_data['BID_DISCOUNT'] = new_data['BID_DISCOUNT'].astype(float)
new_data['BID_MARGIN'] = new_data['BID_MARGIN'].astype(float)
new_data['BID_MARGIN_TOTAL'] = new_data['BID_MARGIN_TOTAL'].astype(float)

In [33]:
new_data.dtypes

MONTH                    int64
BID_ID                  object
SOURCE_SYS_CD           object
PRICE_TO_BP            float64
BID_MARGIN_TOTAL       float64
BID_MARGIN             float64
BID_DISCOUNT           float64
STOP_BIDS                int64
BPCOPS                   int64
MISSING                  int64
CONFIDENTIALITY         object
ROUTE_TO_MARKET         object
NON_COMPETITIVE_BID     object
OFF_SHORE_PMT_TERMS     object
BUNDLED_SOLUTION        object
CONTINGENCY_FEE         object
FOCUS                    int64
HW_SW                   object
COUNTRY_AE               uint8
COUNTRY_AF               uint8
COUNTRY_AL               uint8
COUNTRY_AM               uint8
COUNTRY_AO               uint8
COUNTRY_AR               uint8
COUNTRY_AZ               uint8
COUNTRY_BA               uint8
COUNTRY_BD               uint8
COUNTRY_BF               uint8
COUNTRY_BG               uint8
COUNTRY_BH               uint8
                        ...   
COUNTRY_PE               uint8
COUNTRY_

In [34]:
X = new_data.drop(['FOCUS','BID_ID'],axis = 1).values
Y = new_data['FOCUS'].values

In [35]:
X

array([[4, 'OPRA', 34236.8, ..., 0, 0, 0],
       [9, 'OPRA', 58588.02, ..., 0, 0, 0],
       [6, 'OPRA', 57095.8465, ..., 0, 0, 0],
       ...,
       [9, 'BH', 24584.68, ..., 0, 0, 0],
       [9, 'BH', 191816.76, ..., 0, 0, 0],
       [11, 'OPRA', 226953.198, ..., 0, 0, 0]], dtype=object)

In [36]:
Y

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [37]:
labelencoder_X_1 = LabelEncoder()

X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
X[:,9] = labelencoder_X_1.fit_transform(X[:,9])
X[:,10] = labelencoder_X_1.fit_transform(X[:,10])
X[:,11] = labelencoder_X_1.fit_transform(X[:,11])
X[:,12] = labelencoder_X_1.fit_transform(X[:,12])
X[:,13] = labelencoder_X_1.fit_transform(X[:,13])
X[:,14] = labelencoder_X_1.fit_transform(X[:,14])
X[:,15] = labelencoder_X_1.fit_transform(X[:,15])

In [38]:
X

array([[4, 3, 34236.8, ..., 0, 0, 0],
       [9, 3, 58588.02, ..., 0, 0, 0],
       [6, 3, 57095.8465, ..., 0, 0, 0],
       ...,
       [9, 0, 24584.68, ..., 0, 0, 0],
       [9, 0, 191816.76, ..., 0, 0, 0],
       [11, 3, 226953.198, ..., 0, 0, 0]], dtype=object)

In [39]:
x_train, x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.3,random_state = 10)

In [45]:
y_train

array([1, 0, 0, ..., 0, 0, 1], dtype=int64)

In [46]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

C:\Users\PranaviPadegal\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [47]:
model_logr = LogisticRegression()

In [48]:
model_logr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [49]:
y_predict = model_logr.predict(x_test)
print(classification_report(y_test,y_predict))

             precision    recall  f1-score   support

          0       0.88      0.94      0.91      6251
          1       0.75      0.57      0.65      1971

avg / total       0.85      0.85      0.85      8222



In [50]:
confusion_matrix(y_test,y_predict)

array([[5876,  375],
       [ 839, 1132]], dtype=int64)

In [51]:
print(accuracy_score(y_test,y_predict))

0.8523473607394795


In [52]:
model_mlp = MLPClassifier(hidden_layer_sizes=(100,100,100),batch_size=10,learning_rate_init=0.01,max_iter=2000,random_state=10)
model_mlp.fit(x_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size=10, beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 100, 100), learning_rate='constant',
       learning_rate_init=0.01, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=10, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [53]:
y_ann_predict = model_mlp.predict(x_test)

In [54]:
print(classification_report(y_test,y_ann_predict))

             precision    recall  f1-score   support

          0       0.91      0.96      0.93      6251
          1       0.86      0.68      0.76      1971

avg / total       0.89      0.90      0.89      8222



In [55]:
confusion_matrix(y_test,y_ann_predict)

array([[6032,  219],
       [ 629, 1342]], dtype=int64)

In [56]:
print(accuracy_score(y_test,y_ann_predict))

0.896862077353442


In [57]:
svc_linear = svm.SVC(kernel='linear',C=1)

In [58]:
svc_linear.fit(x_train, y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [60]:
y_svm_predict = svc_linear.predict(x_test)
cnf_matrix = confusion_matrix(y_test, y_svm_predict)
print(cnf_matrix)

[[5907  344]
 [ 826 1145]]


In [61]:
print(classification_report(y_test,y_svm_predict))

             precision    recall  f1-score   support

          0       0.88      0.94      0.91      6251
          1       0.77      0.58      0.66      1971

avg / total       0.85      0.86      0.85      8222



In [62]:
print(accuracy_score(y_test,y_svm_predict))

0.8576988567258574


In [77]:
Y_train = np.array(y_train)
listvalues = []
listvalues.append(Y_train)
listvalues.append(y_test)
listvalues.append(y_svm_predict)


In [78]:
import collections 

counter = []
for i in range(len(listvalues)):
    counter.append(collections.Counter(listvalues[i]))

In [79]:
counter

[Counter({1: 4657, 0: 14527}),
 Counter({0: 6251, 1: 1971}),
 Counter({0: 6733, 1: 1489})]

In [82]:
(4657)/(14527+4657)

0.24275437864887406

In [83]:
(1971)/(6251+1971)

0.2397226952079786

In [84]:
(1489)/(6733+1489)

0.18109948917538313